name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: welcome page
          run: echo "my first github actions porject"

        - name: List files
          run: ls

        - name: readme file
          run: cat README.md
