name: generate-ascii artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: execute cowsay program
          run: coway -f cow "Run for cover, I am a COW....RAWR" >>cow.tx
          
        - name: read file
          run: cat cow.txt   